### ISSUE TITLE
Dropdown menu Submission Details > Species has only 'Test' option

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/ogre#6]
I imagine this is because the tool is still under development, but just to keep track of things here: when creating a new submission, the dropdown menu has only the 'Test' species.

**Comment by williamdlees** [comment]
Thanks Susanna. You're right - but I have added Human and Mouse now. 'Test' is special in that all registered users are effectively members of the 'Test' committee and will see submissions when they are made, and can take them through the review process.
